---
title: "Astrophotography"
author: "Atsushi Kawai"
date: "2018/11/18"
output: html_document
---

天体写真撮影用のノート

#暫定方針
+ ノートはWindows/Macで共有するためGitHubで管理
+ 撮影はWindowsノートPCでステラショットを用いて行う
+ 撮影画像の天体名は天体写真リスト.ooutline
+ 撮影時のログは天体観測ログ.ooutline
    + 月齢はここでhttp://www.calc-site.com/search_dates/11/15/2018
+ 処理前画像管理はLightRoomで行う。Windows/Macでできるように外付けHDDで管理
    + 明らかな失敗画像は消す。
    + 処理しないと決めたNEF画像は消す。
    + 画像処理の練習台/作品になりそうなJPG/NEFは残す
    + 調整用画像は必要ならJPGを残す NEFは消す
    + テスト露出はJPG/NEFを残す
    + ぶれ/ボケ画像は露出の参考になりそうなもののみ残す
    + ちゃんとしたデータが取れたら古いNEFは消す。JPGはそれなりのもののみ残す

--------------------------------------------------------------------------------


+ 今までに準備したことを挙げる
+ 観測準備ですべきことを挙げる
+ 画像処理ですべきことを挙げる
+ 将来的にやりたいことを挙げる

項目ごとに分けて挙げて、ToDoリストをまとめる

#To do
+ 過去のメモの記述を統合・ファイルを整理
+ 過去の撮影画像のログ・取捨選択
    + 20181115から遡って20180726まで完了

+ 過去の撮影画像から今後の観測のためのデータを抽出
    + 空の明るさ/露出時間/月齢/観測地/天体の明るさ
空の明るさ確認用NEF画像
+ 逗子自宅
+ 伽藍山
+ 太郎坊
+ 須走口
    + 20110907 D3,D3s,14mm,24mm
    + 20110929 D3s, 80mm,200mm
+ 富士山?駐車場
+ 洗足池
    + 20110521 D3s 満月
+ 城ヶ島
    + 20110712 D90
+ 天狗高原
    + 20110729 D3s,D3x
+ 浅間運動公園
    + 20120218 D700
    + 20120324 D700

+ 観測時の問題点/不便な点/不明な点を解決

+ 副鏡固定によるフレア確認
+ フラットのゴミ原因追求
+ ノートPC用外部バッテリーテスト

+ qlnefでフラットフィールディングがうまくいかない?
    + 暗いところのS/Nが悪い -> 複数合成フラット
    + ダーク成分を持ち上げている? -> ダーク除去を検討
    + 表示を再考
    + 他のふらっとありデータでも確認

+ ステラショット
    + 保存ファイル名
    + 自動撮影
    + オートガイダー

+ フィルタ特性整理
    + ソフトフォーカスフィルタ
    + 光害カットフィルタ
    + ADNB Astro Duo Narrow Bandフィルタ 視野ケラレ?

+ 星像
    + フォーカサーの目盛り
    + バーチノフマスクのパターンと星像の関係
    + 光軸調整 焦点内外画像のパターンと星像の関係
    + ドリフトアライメント前後で伸びる方向を確認 20181115
    
+ 天体
    + テスト撮影した天体の撮影条件と見た目/サイズ/明るさの一覧 Rmdで？ooutlineで？
    　Shinyで観測準備用アプリをつくりたい

+ 画像処理テーマごとにデータの場所を整理

+ Photoshop現像
    + 20110712 帰りのSA 朝焼けと木
    + 20120512 D7000+300mmx2 太陽
    + 20120521 D700+85mm 月暈
    
+ 位置合わせ/明るさ調節/解像選別
    + 20110320 D90+500mm 満月 良いのを選ぶ / 合成
    + 20110521 D3s+500mm 月 数多い
    + 20110712 D3s+500mm 月 4枚のみ
    + 20120320 D7000+300mmx2 太陽
    + 20120512 D3s+300mmx2 太陽

+ 複数画像NR / HDR
    + 20110521 D3s+24mm 月と洗足池
    + 20120218 D700+35mm Leo ソフトフォーカスフィルタ/絞り変化
    + 20120324 D700+85mm CrB,Lyr,Sco ソフトフォーカスフィルタ

+ 位置合わせ+複数画像合成
    + 20110729 D3s+24mm Sco/Sgr周辺の天の川
    + 20110729 D3x+24mm Sco/Sgr周辺の天の川 451枚
    + 20110907 D3+24mm  御殿場/富士山方向 色々なパターンで600枚強
    + 20110907 D3s+80mm M45
    + 20110929 D3s+80mm,200mm Ori
    
+ タイムラプス
    + 20110729 D3x+24mm Sco/Sgr周辺の天の川 451枚
    + 20110907 D3+24mm  御殿場/富士山方向 色々なパターンで600枚強
    + 20110907 D3s+14mm他 富士山方向
    + 20120326 D700+48mm 洗足池に沈む金星,三日月,木星 要露出調整
    + 20120521 D700+14mm 金環食中の撮影風景
    + 20120521 D7000+300mmx2 金環食
    
ダーク除去
    + これ以前は未確認
    + 20120326 D700+48mm 洗足池に沈む金星,三日月,木星 要露出調整
    
    
    
#To do in the future...
+ コリメート法
+ 惑星動画撮影
+ ベランダを拡張したい

***

#観測準備
##観測地
+ 逗子自宅
+ 伽藍山
+ 太郎坊
+ 須走口
+ 富士山?駐車場

+ それぞれの観測地の明るさをカメラ/月齢と共に過去の撮影画像からリストアップ

***

##ターゲット

***

##ハード

###R200SS
+ 20180311 電動フォーカサー導入
+ 20180311 副鏡が固定されていないことが発覚 どうりで光軸がずれるわけだ...
+ 20180317 光軸調整用のねじをBob's Knobに交換
+ 20180317 白の熱可塑性プラスチックで副鏡固定機構を作成
+ 20180421 木星を撮影すると斜めのフレアが...
+ 20180820 黒の熱可塑性プラスチックで副鏡固定機構を作成

###SXP/StarBOOKTEN
+ 201808?? STARBOOK TENのコントロールが効かなくなった 
           分解してフラットケーブルを挿し直して解決
           
###D810A

###カメラレンズ
+ 20110712 FXでDXレンズの視野を確認
+ 20180207 手ぶれ補正で星が伸びるので注意

###フィルタ
####STC Astro Duo Narrow Band Filter
+ 20180817 テスト撮影 カメラレンズでは抑えられるが、望遠鏡ではフィルタが固定できない
+ 20180820 黒の熱可塑性プラスチックで抑えを作成

###オートガイダ

###PC/ケーブリング
+ 20180224 R232cケーブル断線/交換
+ 20180421 PCバッテリが3hで切れる
+ 20180817 D810の接続が不安定に
    + 右のUSBポートの電源不足のため？左にすると解消
+ 20180820 チューブでケーブルをまとめると、重さがまして負担が大きそうなのでやめた
+ 20180820 マジックテープによるケーブル固定 今の所良さそう

***

##ソフト

###ステラショット

###PHD Guiding
+ 20180820 PHD Guiding2 + ASCOM接続に変更 時々コマンドエラーが出ているが？
+ 20181115 ドリフトアライメントで赤緯方向の補正が不要になり星像改善？要確認  
+ 20181115 ドリフトアライメントは赤道儀のメモリを見た方が良さそう

###自作ソフト


##画像処理

###LightRoom

###Photoshop

###自作ソフト



***

#ログ
天体観測ログ.ooutlineにまとめる

***

#将来計画

##ベランダ拡張
+ 20181102 魚眼レンズで視界確認する画像を撮影