---
title: "Astrophotography"
author: "Atsushi Kawai"
date: "2018/11/18"
output: html_document
---

天体写真撮影用のノート

+ 使えそうなRパッケージの確認 astro/RforAstronomy.Rmd
+ 天体リスト astro/Object.Rmd

+ ターゲットリストを作成
+ 観測ログを作成 ターゲットごとにどの視野・波長でどのS/Nまで撮影したか
+ 観測値リスト作成して空の明るさを記録 日付と時間・座標から月までの距離も計算
+ 星図の位置を指定して座標を出力する
    + 製図表示はShinyでできる？
+ 画像の位置を指定して明るさを出力
+ カメラのノイズとゲインを計測
+ 最適露出を決める 観測地/月齢/波長に依存

作るプログラム
+ 指定領域の画素値をダンプ->統計解析
+ 指定領域の平均値を出力
+ 星を検出して周辺の画素値をダンプ->Rで回帰
+ 星の大きさHWDを出力
+ ベイヤー/補間/縮小補間画像での値を選択できるように



#暫定方針
+ ノートはWindows/Macで共有するためGitHubで管理
+ 撮影はWindowsノートPCでステラショットを用いて行う
+ 撮影画像の天体名は天体写真リスト.ooutline
+ 撮影時のログは天体観測ログ.ooutline
    + 月齢はここでhttp://www.calc-site.com/search_dates/11/15/2018
+ 処理前画像管理はLightRoomで行う。Windows/Macでできるように外付けHDDで管理
    + 明らかな失敗画像は消す。
    + 処理しないと決めたNEF画像は消す。
    + 画像処理の練習台/作品になりそうなJPG/NEFは残す
    + 調整用画像は必要ならJPGを残す NEFは消す
    + テスト露出はJPG/NEFを残す
    + ぶれ/ボケ画像は露出の参考になりそうなもののみ残す
    + ちゃんとしたデータが取れたら古いNEFは消す。JPGはそれなりのもののみ残す

+ 処理後のNEFは倉庫的なディレクトリに集約
+ もう行かない観測値のスカイレベルは参考程度に収集

--------------------------------------------------------------------------------


+ 今までに準備したことを挙げる
+ 観測準備ですべきことを挙げる
+ 画像処理ですべきことを挙げる
+ 将来的にやりたいことを挙げる

項目ごとに分けて挙げて、ToDoリストをまとめる

#To do

+ 外付けバッテリー
+ Stellarmate設定
+ 明るさ・星像の記録とガイドのログを分析
+ バイアス/ゲイン/ダーク特性を把握
+ フラット必要露出を確認
+ 天体明るさ確認
+ ターゲットリスト
+ Shinyアプリ
+ PHDG2マニュアル再確認 Declination Backlashの意味は？

+ 過去のメモの記述を統合・ファイルを整理
+ 過去の撮影画像のログ・取捨選択
    + 20181115から遡って20180726まで完了

+ ._DSC*.JPG,xmpなどはWindowsでできたファイル？スクリプトで消す
+ タイムラプス素材はLrで条件ごとにフォルダを分ける

+ 過去の撮影画像から今後の観測のためのデータを抽出
    + 空の明るさ/露出時間/月齢/観測地/天体の明るさ
空の明るさ確認用NEF画像
+ 逗子自宅
    + 20160501 D810A
    + 20160504 D810A
    + 20160515 D810A
    + 20160519 D810A
    + 20160521 D810A
    + 20160529 D810A
    + 20160611 D810A
    + 20160706 D810A
    + 20171204 D810A 魚眼
    + 20171216 D810A + 300mm
    + 20171222 D810A + 500mm
    + 20180207 D810A + 500mm
    + 20180325 D810A + 760mm
    + 20180331 D810A + 760mm 短時間　
    + 20180421 D810A + 760mm
    + 20180729 D810A + 760mm 短時間
    + 20180822 D810A + 760mm ADNB 短時間
    + 20180825 D810A + 760mm ADNB
    + 20180826 D810A + 760mm ADNB
    + 20181102 D810A + 魚眼
    + 20181114 D810A + 760mm 
    + 20181115 D810A + 760mm
    + 20190308 D810A + 1120mm ADNB
    + 20180324 D810A + 1120mm ADNB
+ 逗子新宿湾
    + 20160831 D810A 明るい
+ 披露山
    + 20170520 D810A
+ 小坪マリーナ
    + 20170902 D810A 魚眼
+ 伽藍山
    + 20151216 D810A+35mm
    + 20160211 D810A+760mm
    + 20160730 D810A
    + 20161016 D810A
    + 20161103 D810A
+ 太郎坊
    + 20151018 D810A+760mm
+ 須走口
    + 20110907 D3,D3s,14mm,24mm
    + 20110929 D3s, 80mm,200mm
    + 20120819 D700,D800E
    + 20121019 D700,D800E
+ 西臼塚
    + 20121213 D700,D800,D800E
    + 20131201 D700
+ 洗足池
    + 20110521 D3s 満月
+ 城ヶ島
    + 20110712 D90
+ 天狗高原
    + 20110729 D3s,D3x
+ 浅間山運動公園
    + 20120218 D700
    + 20120324 D700
    + 20120316 D800
+ 琵琶湖湖岸
    + 20120815 D700+14mm
+ 海ほたる 薄明中なので参考以下？
+ 大船自宅
    + 20130827 D700
    + 20140726 D700 R200SSテスト
    + 20140818
    + 20150110 D700
    + 20150712 D800
    + 20150912 D810A
    + 20151013 D810A
    + 20151221 D810A
+ Tikehau
    + 20130905 D800E
+ Lillehammer
    + 20170914 JPGのみ
+ Burllingame 
    + 20180131 月食

+ 観測時の問題点/不便な点/不明な点を解決

+ 副鏡固定によるフレア確認
+ ノートPC用外部バッテリーテスト

+ qlnefでフラットフィールディングがうまくいかない?
    + 暗いところのS/Nが悪い -> 複数合成フラット
    + ダーク成分を持ち上げている? -> ダーク除去を検討
    + 表示を再考
    + 他のふらっとありデータでも確認

+ ステラショット
    + 保存ファイル名
    + 自動撮影
    + オートガイダー

+ フィルタ特性整理
    + ソフトフォーカスフィルタ
    + 光害カットフィルタ
    + ADNB Astro Duo Narrow Bandフィルタ 視野ケラレ?

+ 星像
    + フォーカサーの目盛り
    + バーチノフマスクのパターンと星像の関係
    + 光軸調整 焦点内外画像のパターンと星像の関係
    + ドリフトアライメント前後で伸びる方向を確認 20181115
    + 20151221 焦点外像と星像をテスト
    + 20160529 焦点外像と星像をテスト
    + 20171222 ピリオディックモーション
    + 20180421 木星のフレア?
    + 20180729 火星のフレア?
    + 20190324 透明バーチノフマスク例
    
+ 天体
    + テスト撮影した天体の撮影条件と見た目/サイズ/明るさの一覧 Rmdで？ooutlineで？
    　Shinyで観測準備用アプリをつくりたい
    　
+ 露出レベルテスト

+ 画像処理テーマごとにデータの場所を整理

+ Photoshop現像
    + 20110712 帰りのSA 朝焼けと木
    + 20120512 D7000+300mmx2 太陽
    + 20120521 D700+85mm 月暈
    + 20121019 黄道光
    + 20130316 海ほたる/ ISON彗星
    + 20130903 雲越しの銀河
    + 20130904 雲越しの銀河
    + 20150110 ラヴジョイ彗星
    + 20160806 夕焼け
     
+ 位置合わせ/明るさ調節/解像選別
    + 20110320 D90+500mm 満月 良いのを選ぶ / 合成
    + 20110521 D3s+500mm 月 数多い
    + 20110712 D3s+500mm 月 4枚のみ
    + 20120320 D7000+300mmx2 太陽
    + 20120512 D3s+300mmx2 太陽
    + 20120606 D7000+300mmx2 金星日面通過
    + 20120606 V1+300mmx2 金星日面通過 エッジで追う？
    + 20150928 D810A+500mm 月
    + 20151221 D810A+760mm 月
    + 20180421 D810A+760mm 木星
    + 20180729 D810A+760mm 火星
    
+ 位置合わせ+複数画像合成NR / HDR
    + 20110521 D3s+24mm 月と洗足池
    + 20110729 D3s+24mm Sco/Sgr周辺の天の川 x40
    + 20110729 D3x+24mm Sco/Sgr周辺の天の川 451枚
    + 20110907 D3+24mm  御殿場/富士山方向 色々なパターンで600枚強
    + 20110907 D3s+14mm,80mm,200 M45 富士山方向
    + 20110929 D3s+80mm,200mm Ori
    + 20120218 D700+35mm Leo ソフトフォーカスフィルタ/絞り変化
    + 20120324 D700+85mm CrB,Lyr,Sco ソフトフォーカスフィルタ
    + 20120819 D700+85mm Cas,Cyg
    + 20121019 D800E+35mm Ori
    + 20121213 D800+35mm,85mm Ori
    + 20130905 D800E+14,24,35mm 天の川/大小マゼラン雲 
    + 20131201 D800E+ Ori
    + 20151013 D810A+760mm M31
    + 20151018 D810A+760mm NGC7000, γ Cyg, NGC1499
o    + 20160211 D810+14,24,85mmでOri
    + 20170730 D810A+760mm M21
    + 20180131 D810+ 月食
    + 20180331 D810A+760mm 月
    + 20180421 D810A+760mm Leo triplet, M64
    + 20180822 M27 AGなし
    + 20180825 NGC7293 AGあり
    + 20180826 NGC7009 AG/F/D
    + 20181114 M77 AG/F/D
    + 20181114 NGC253,NGC246,M77 AGDA/F/D

+ タイムラプス
    + 20110729 D3x+24mm Sco/Sgr周辺の天の川 
        + TL_ScoSgr_24mm_f2.8_ISO1600_1s_440
    + 20110907 D3+24mm  御殿場/富士山方向 64x9
    + 20120326 D700+48mm 洗足池に沈む金星,三日月,木星 要露出調整149
    + 20120521 D700+14mm 金環食中の撮影風景
    + 20120521 D7000+300mmx2 金環食 エッジで追う？
    + 20120819 D700+14mm,24mm 御殿場/富士山方向 60x6
    + 20121019 D800E+35mm CasPerAnd,Ori
    + 20121213 D700+14mm 北天
    + 20130905 D800E+14mm 礁湖越しの黄道光と天の川
    + 20151216 D810A+35mm 雲越しのOri
    + 20160730 D810A+14mm 雲越しの天の川
    + 20161103 D810A+24mm 夏の大三角

+ フラット補正
    + 20161016 フラットのみ？
    + 20180421 Let Tripelt, M64
    + 20180822 M27 ADNB AGなし Fあり
    + 20180825 NGC7293 AGあり Fあり Dあり
    + 20180826 M17, M16
    + 20181114 M77 AG/F/D
    + 20181114 NGC253,NGC246,M77 AGDA/F/D
    + 20190308 NGC2359, IC2166, ハッブルの変光星雲, NGC2264, M46+NGC2348
               NGC2392, NGC2903, Leo Quartet, Leo Triplet

+ ダーク除去
    + これ以前は未確認
    + 20120326 D700+48mm 洗足池に沈む金星,三日月,木星 要露出調整
    
#To do in the future...
+ コリメート法
+ 惑星動画撮影
+ ベランダを拡張したい

***

#観測準備
##観測地
+ 大船5-2-8	   35°20'54" 139°32'21"
+ 鎌倉市民農園 35°20'59" 139°32'48"	
+ 須走口駐車場 35°21'54" 138°46'35"	
+ 西臼塚駐車場 35°17'54" 138°43'02"
+ 太郎坊駐車場 35°20'03" 138°47'46"

+ 逗子自宅
+ 伽藍山
+ 太郎坊
+ 須走口
+ 富士山?駐車場

+ 石垣島川平 24°27'41" 124°08'29"
+ 西表島祖納 24°23'24" 123°44'50"

+ それぞれの観測地の明るさをカメラ/月齢と共に過去の撮影画像からリストアップ

***

##ターゲット

***

##ハード

###R200SS
+ 20140726 ファーストライト
+ 20150101 光軸ズレを認識しつつ太郎坊と伽藍山へ
+ 20160211 観測中に姿勢さでピンと大きくずれたことがあった?
+ 20160529 光軸調整して？星像確認
+ 20161016 フラット導入
+ 20161016 ピンと大きくずれたのはこの時? 姿勢によりコマが目立つことを認識
+ 20180311 電動フォーカサー導入
+ 20180311 副鏡が固定されていないことが発覚 どうりで光軸がずれるわけだ...
+ 20180317 光軸調整用のねじをBob's Knobに交換
+ 20180317 白の熱可塑性プラスチックで副鏡固定機構を作成
+ 20180421 木星を撮影すると斜めのフレアが...
+ 20180820 黒の熱可塑性プラスチックで副鏡固定機構を作成
+ 20190223 直焦ワイドアダプター60DXを導入 硬くてグラグラしない ネジは干渉するので交換
+ 20190303 エクステンダーPHの取り付けをテスト
+ 20190303 アダプタなし/コレクターPH/エクステンダーPHでフラットを確認 ピントはあってないかも
           アダプタなしがケラレは一番少ない
           コレクターPHだとアダプタ+ミラーボックスのケラレ
           エクステンダーPHだとアダプタのケラレ
           F値が大きいほうがセンサのゴミが目立つ
+ 20190305 クリップフィルターありだとピントが違いすぎてよくわからない 現像もうまくいってない？

+ 20190324 透明バーティノフマスク αCMiで一応できた。

###SXP/StarBOOKTEN
+ 20171222 ピリオディックモーション測定
+ 201808?? STARBOOK TENのコントロールが効かなくなった 
           分解してフラットケーブルを挿し直して解決
           
###D810A

###カメラレンズ
+ 20110712 FXでDXレンズの視野を確認
+ 20120218 ソフトフォーカスフィルタ導入
+ 20170902 魚眼レンズ導入
+ 20180207 手ぶれ補正で星が伸びるので注意
+ 20181102 魚眼ズーム広角端フード外さないと蹴られる
+ 20190305 センサクリーニング クリーニング液使わなくても落ちた

###AstroTrack

###ポラリエ

###フィルタ
####STC Astro Duo Narrow Band Filter
+ 20180817 テスト撮影 カメラレンズでは抑えられるが、望遠鏡ではフィルタが固定できない
+ 20180820 黒の熱可塑性プラスチックで抑えを作成
+ 20180223 直焦ワイドアダプター60DXに交換すると抑えが入らなくなったので再作成が必要
+ 20180302 抑えを再作成 2分割にしてけられないようにしてみた

###オートガイダ
+ 20180206 D810A+500mmでオートガイド調整 レンズの手ぶれ補正で星像が延びた
+ 20180207 D810A+500mmでオートガイド調整 PHDガイディングでドリフトアライメント
+ 20181115 D810A+760mm ドリフトアライメント　架台の目盛りを信用するのが良さげ

+ 20190724 D810A+1120mm 240mmでガイド 
    + RA agrを100にするとキになりにくい？
    + 調子がいい時は1"切るが、時々乱れて1.8"に...
    + RA,DEC両方振動する感じ 特にDECが長い
    + 姿勢差ではない?
    + バイクが通っても揺れない
    + 車？人の振動?くしゃみ？飛行機?
    
###フラット
+ 20190308 フラットのゴミ原因追求 -> センサーのゴミが原因だった

###PC/ケーブリング
+ 20180207 USBケーブルが不安定？
+ 20180224 R232cケーブル断線/交換
+ 20180421 PCバッテリが3hで切れる
+ 20180817 D810の接続が不安定に
    + 右のUSBポートの電源不足のため？左にすると解消
+ 20180820 チューブでケーブルをまとめると、重さがまして負担が大きそうなのでやめた
+ 20180820 マジックテープによるケーブル固定 今の所良さそう
+ 20181210 HDDバックアップしたけどだいぶファイルがなくなってる...

+ 20190308 オートガイダとD810Aを同時につなぐと画像が取得できなくなった...
           家ではmacでガイドをすればいいが外では？ Raspbery Piでいってみるか？

###Stellarmate
HotSpot Password: stellar@mate
Hostname: stellarmate.local HotSpot接続の場合はhttp://10.250.250.1:8624
username: stellarmate
password: smate

+ 20180317 Lenovoでガイドできなくなったので発注
+ 20180322 電源入れたけどディスプレイが映らない...
           microSDがmacで認識されない? Winでは認識されたがフォーマットが違う
           Hotspotで接続->sshでログインして、設定を修正
           + stellarmate ネットワークキー？ stellar@mate
           + ssh -l stellarmate stellarmate.local -p / pass smate
           + /boot/config.txtのhdmi_safe=1をコメント外す
+ 20180324 iPadからHotSpotでログインできなかったが、リセット繰り返すとできるようになった。
+ 20190401? StarbookTenに未対応？アップデート必要？ガイダ動作したが設定がうまく行っていない D810Aはよくわかんない
  

###設営
+ 20180224 すのこ導入
***

##ソフト

###CameraControlPro2
+ 20120329? 

###ステラショット
+ 20190314 エラーウインドウが出まくった。
+ 201903?? 起動しても全く反応しなくなった。
           再インストール・システム復元では解決せず。
           レジストリまで完全消去して再インストールで戻った。
+ 20190324 最初Starbook Tenとの接続がうまくいかなかったが、観測できるようになった。

###PHD Guiding2
+ 20180820 PHD Guiding2 + ASCOM接続に変更 時々コマンドエラーが出ているが？
+ 20181115 ドリフトアライメントで赤緯方向の補正が不要になり星像改善？要確認  
+ 20181115 ドリフトアライメントは赤道儀の目印を見た方が良さそう
+ 20190405 ExtenderPH導入するとオートガイドの精度が目立ってきた
           100mm+QHY-5IIMでRMS=1.7-2.0arcsec  2-3pix 15-20arcsec
+ 20190407 800mm+QHY-5IIMでRMS=0.6-1.0arcsec 4pix 4-5arcsec?
           同じ明るさだと星像サイズに比例する感じか？
           ガイドアシスタント出力例
```
赤経 -10.62arcsec/m max 0.45arcsec/s
赤緯 0.79arcsec/m
Declination Backlash 254+-135ms 3.8+-2.0arcsec
```
            ガイド露出時間あたりの赤緯ドリフト<検出精度以上に合わせても意味がなさそう
            1arcsec/s -> 60arcsec/m 1arcsec/mを切っていればよしとするか
            USB繋いでから動作するまでに時間が必要？
+ 20190415 
0.10, 0.15でRMS1そこそこ？ 極軸もっと追い込める ピント合わせてから
フォーカス62-63mm(57-58mm定規)
```
赤経 5.62arcsec/m max 0.45arcsec/s
赤緯 3.40arcsec/m
極軸設定エラー >13arcmin
Declination Backlash 254+-135ms 3.8+-2.0arcsec
```

###自作ソフト
+ 20181201? dcrawがメモリ関連で不正終了することがあったので最小限の構成で改修
+ 20190201? Windowsでdcrawがコンパイルできなくなっていたので原因追求/修正
            glibcの関数を自前で定義する部分が含まれていなかったため

##画像処理

###LightRoom

###Photoshop

###自作ソフト



***

#ログ
天体観測ログ.ooutlineにまとめる

***

# 観測手順

+ 設置
+ バランス
+ ケーブリング
+ 電源ON
+ ステラショット起動/接続
+ 天の赤道付近の恒星を導入
+ フォーカス確認(大体)
+ PHD2起動/接続
+ ガイドkyo

  + 方位角 
      + 左を締めると直線が下がる
      + 右を閉めると視野がEに動き,直線があがる
  + 高度角 CWで視野が北に動き、直線が上がる
  
# 20190725
+ SXP設定 X-Yだとエラーが大きかった
+ ピリオディックモーションを抑えるには1s補正が必要
+ 閾値も大きすぎると追従できない
+ 電動フォーカサーの精度ではピント合わせきれない
+ RA方向に伸びやすいので、DEC方向に伸びるピントにしておくのがベター？
+ 高度角まで設定
+ 170くらいのガイド星で<0.8"の星像を達成？

+ ISO12800, 300sで右上にアンプノイズ？

+ mac mini -> hp IPv4が設定されていないと繋がらない? 再起動

+ Lightroomで読み込み
+ JPGとNEFが同じフォルダにあればまとめて扱える
+ 調整時のjpgは不要なものは消してsetup以下に移動
  気づいた点をログに記す->このファイルに転記
+ 失敗フレーム ガイドエラーで星が二重/流れるなどは★1つでtbd以下に移動
    + 現像終了後、廃棄する
+ MEF/タイムラプスは対象ごとにディレクトリを分ける。カメラJPGは消去
    + NEFをあとから動かすと現像できない
+ CF経由でコピーすると壊れたNEFがあった。SSDでするのがいいかも

# ファイル/ログ整理方針
+ 日付/機材ごとにディレクトリを分ける
+ 対象/内容ごとにサブディレクトリを分ける
+ 不要ファイル削除後、カメラJPGをjpg0に移動or消去

# To do
+ 手動フォーカサーに戻してベストフォーカス出せるか確認
+ リモートで動かせる高精度電動フォーカサー？
+ 視野回転の位置決め/方向を整理
+ ガイド鏡の向きをずらすためのネジ操作方向を確認
+ ノートPC外部バッテリー
+ flatの明るさ・枚数を確定
+ ノイズ特性と空の明るさから最適露出枚数を計算

+ -i 入力画像リスト
+ -E で評価エリアを元画像座標で指定
+ -D scale でscale倍して表示
+ -S スタック表示
+ -A 並べて表示
+ -b 分離したbayerも表示
+ -g ガンマ
+ -z z1,z2 表示レベル

# ファイル整理方針
+ 撮影後
    + ダークはdark以下にまとめてjpgは消去
    + 調整時の画像はtest以下に 不要なものは消す
    + テーマごとにディレクトリを作成してjpg,nefを移動 フラットも
    + 次のターゲット候補のテスト撮影はtarget以下に 不要なものは消す
    + 観測時のflat.tifなど、不要だが現像まで一応残しておくものはtbd以下に移動
    + ここまで終わったらログのディレクトリ整理をチェック
    + ここで元画像管理用にLrに読み込み

+ 現像処理
  + 詳細はこれから

+ 現像処理後
    + 完成画像をLrカタログに読み込み
        + 完成画像ログに詳細を記述
    + 画質の劣るjpgと 不要だったnefは消去
    + ここまで終わったらログの現像をチェック
  
+ 解析
    + 日時,場所,月齢,方位と高度,機材と空の明るさを観測値データに追加
    + 日時,場所,月齢,方位と高度,機材と天体の明るさをターゲットデータに追加
    + 日時,場所,月齢,方位と高度,機材,ガイドログ,像高,合焦情報と星像サイズを星像データに追加 
    + 観測可能な方位と高度をベランダデータに追加
    + ここまで終わったらログの解析をチェック
***

#将来計画

##ベランダ拡張
+ 20181102 魚眼レンズで視界確認する画像を撮影