---
title: "Camera"
output: html_notebook
---

カメラのキャリブレーションデータ検討
+ センサー読み出しノイズ・ゲイン
+ バイアスのノイズ統計/RTSノイズ
+ ダークノイズ

```{r setup}
library(tidyverse)
library(patchwork)
library(ggpubr)
```

#読み出しノイズ/ゲイン
+ sigma_rn_e
+ sigma_s_e = sqrt(s_e)
+ adu_per_e

p = p_e * adu_per_e
p_e = s_e + n_e
sigma_e = sqrt(sigma_rn_e^2 + s_e)
n_eは平均が0の分布とする

s_e = s / k
sigma_e^2 = sigma^2 / k^2 = n^2 + s/k

k(e/ADU)
s = s_e / k
sigma = sigma_e / k = sqrt(sigma_rn_e^2 + s_e) / k
= sigma_rn_e / k (t=0)
=sqrt(C/k) (t>>0)

sigma_rn_e = sigma * k
k = C / sigma^2

sd_p = sqrt(n^2/k^2 + mean_p / k)
```{r fig.height = 3, out.width="100%"}
n_sample <- 1000
adu_per_e <- 20
sigma_rn_e <- 5
s_e_levels <- c(0.0, 1 * 2^(0:14))
dat <- tibble()
for(adu_per_e in c(0.1, 1, 10)) {
  for(sigma_rn_e in c(1, 5, 10)) {
for(s_e in s_e_levels) {
  sigma_e <- sqrt(sigma_rn_e^2 + s_e)
  p_e <- s_e + rnorm(n_sample, 0.0, sigma_e)
  s <- adu_per_e * s_e
  p <- adu_per_e * p_e
  dat <- bind_rows(dat, tibble(adu_per_e, sigma_rn_e, s_e, p_e, s, p))
}
  }
}
dat <- mutate(dat, adu_per_e = factor(adu_per_e), sigma_rn_e = factor(sigma_rn_e),
              Noise = sprintf("%s,%s", adu_per_e, sigma_rn_e))
dat <- filter(dat, p < 2^16)

sdat <- group_by(dat, adu_per_e, sigma_rn_e, Noise, s_e, s) %>%
  summarise(mean_p_e = mean(p_e), sd_p_e = sd(p_e),
            mean_p = mean(p), sd_p = sd(p))

g1 <- ggplot(dat) + geom_jitter(aes(s, p, color = Noise))
g1 <- g1 + facet_grid(adu_per_e ~ sigma_rn_e)
g2 <- ggplot(sdat) + geom_line(aes(s, sd_p^2, color = Noise))
g2 <- g2 + scale_x_log10() + scale_y_log10()
g1 + g2 + theme(legend.position = "none")
filter(sdat, Noise == "1,1") -> tsdat
nls(sd_p ~ sqrt(n^2 / k^2 + mean_p / k), data = tsdat, start = c(n = 1, k = 1))

```