---
title: "Hengband"
author: "Atsushi Kawai"
date: "2019/8/10"
output: html_document
---

http://hengband.ninja-x.jp/murakami/rei/hajimete.html

・ゴーレムorゾンビ＋戦士＋攻撃的な性格
完全戦闘力に特化させた組み合わせです。その分隠密・魔道具使用等の能力はかなり低いですが、 序盤は敵をサクサク倒すことができるでしょう。初めてのプレイには最も適していると思います。
ゴーレムは防御力が高く、ゾンビは攻撃力が高いです。

・ホビット＋盗賊＋仙術
盗賊がもともと敵に見つかり辛いことに加え、種族でさらに隠密を上げた組み合わせです。
性格は特に問いません。魔法が仙術なのは、便利系の魔法に優れるからです。 魔道具は全く問題ありませんし、敵が遭遇する前から起きている ことがほとんどなくなるでしょう。（もとから起きている敵は別ですが）
器用が高いこと、盗賊であることのおかげで序盤から攻撃回数が多く、戦闘力も 問題ありません。 ホビットは能力の割に経験値修正が低いので、序盤のレベル上がりも快適だと思います。

・ドラコニアン＋修行僧＋自然
性格は特に問いません。武器を装備する必要がなく、防御力がレベルの上昇と同時に上がってくれるので、 装備を整える必要性が減ります。耐性も、種族がドラコニアンなことで レベルが上がればいくつか手に入ります。通常打撃も非常に強力なので、一対一の戦い ではほとんど負けることがないでしょう。 また、自然領域は低レベルでも非常に優秀な魔法が多くあります。

・ゴーレム＋アーチャー＋ちからじまん
これも戦闘力特化な組み合わせです。攻撃、防御共に最強クラスと言えるでしょう。
弓を巻物で強化して常に矢を絶やさないようにすれば、向かうところ敵なしです。ただし、 マクロが必須。 

http://roguelike.namekuji.jp/index.html?colum_qa.html

・店で値切り交渉をする　－　いいえ
　　店で買い物時に値切り交渉をするかどうか。非常に煩わしい事になるので「いいえ」に設定する。

・初心者簡単モード　－　いいえ
　　ゲームバランスが大きく変化するので通常は「いいえ」に設定する。

・モンスターは失敗を学習する　－　いいえ
・モンスターはプレイヤーの弱みを突く　－　いいえ
　　戦闘が楽になって若干死ににくくなる。自信のないうちは「いいえ」に設定する。

・元祖の街/クエストと荒野なし　－　いいえ
・小規模な街/荒野なし　－　いいえ
　　変愚蛮怒の魅力が半減するので普通は「いいえ」に設定する。

・（鉄人用）　－　いいえ
　　通常プレイ時は全て「いいえ」が無難。

・伝説のアイテムを取り逃がしても再生成される　－　はい
　　通称「保存モード」。便利なので普通は「はい」に設定する。
　　「はい」に設定すると、アーティファクトは鑑定されないかぎり何度でも再生成される。
　　これを「いいえ」に設定してしまうと、フロアに生成されたアーティファクトは、
　　その発見の有無にかかわらず、一度取り逃すと二度と生成されなくなる。

・能力値にオートローラー使用　－　はい
　　初期能力値をえり好みする機能を使用するかどうかの設定。
　　初期能力値は序盤の展開に大きく影響するため、通常は「はい」に設定する。

・我が家を拡張する　－　はい
　　我が家の保管空間を異なる街間で共有するかどうかの設定。
　　便利な機能なので通常は「はい」に設定する。
　　
　　
　　打撃職なら、腕力、耐久、器用を17、魔法道具に関わる知能を15に設定。
魔法職なら、腕力、耐久、知能を17、盗みの抵抗力に関わる器用を15に設定。
デュアルクラスなら、腕力、耐久、器用を17、知能・賢さ・魅力のうち魔法に使用するものを15に設定。
なお、いらない数値も8までは100%なので8にしておくと良い。

１，キー入力
ローグ風キー配列を使用する
ノートパソコンなどテンキーがない場合はこちらのキー配列が操作しやすい。

常にアイテムを拾う
アイテムを拾うのに１ターン消費していてはもったいない。
通常は「はい」に設定し、自動拾いでふるいにかける。

使うコマンドでアイテムを何でも使える
aかuで何でもかんでも使えるようになる。
慣れると便利なので、積極的に使用することをおすすめする。

２，画面出力
常にプレイヤーを中心に置く
好みにもよるが、周りを把握しやすくなるので「はい」をおすすめする。
アングウィルがものすごく重くなるのが玉に瑕。

魔法や矢の軌道を表示する
射線が通っているか確認しやすくなるので「はい」に設定する。

３，ゲームプレイ・オプション
トラップ感知済みでない場所を表示する
感知区域の把握に便利なので「はい」に設定する。

４，行動中止関係
トラップ完治範囲外に出る直前に行動を中止する
トラップ完治範囲外に出る直前に警告する
トラップは避けるに越したことはない。「はい」に設定するのが安全。
中盤以降は即死のハルマゲドン・トラップが有るので非常に重要。

Ｄ，基本ウェイト量
遠距離攻撃などのエフェクトアニメーションの速度を設定する。
ウェイト2～3に設定が、攻撃の種類と攻撃元を把握しやすくて良いだろう。

Ｈ，低ヒットポイント警告
自分用デッドラインとして設定しておくと良い。
序盤～中盤は50～60%、終盤は70～80%辺りだろう。

Ｗ，ウィンドウフラグ
サブウィンドウに表示できる項目を決められる。
メッセージ履歴、モンスターの思い出、持ち物/装備品　あたりを表示させると便利。

その他
メインウィンドウはマウスで端を引っ張って大きくすると視野が広がって快適。


+ ディニシル 344-408
+ 苦痛のグレイブ 335-590

+ 動 虎殺七丁念仏 890
+ 人 虎殺七丁念仏 890
+ オ 太郎太刀 325-895 災いを招くもの 405-900
+ ト 太郎太刀 325-895 災いを招くもの 405-900
+ 巨 フランテング 390-1100
+ 竜 グアサング 335-850 災いを招くもの 485-1315
+ 邪 スレイヤー 371-623
+ 死 ヴァンパイア・キラー 385-1070
+ 悪 デーモンベーン 335-910 ヴァンパイア・キラー 330-740

+ 属性 破壊の隼の剣
+ 

+ 理力 マエグルス 動/邪/死/竜 >800



